name: CI

on:
  push:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-runner:
    runs-on: ubuntu-latest
    outputs:
      runner-label: ${{ steps.set-runner.outputs.runner-label }}
    steps:
      - name: Set runner
        id: set-runner
        run: |
          runners=$(curl -s -H "Accept: application/vnd.github+json" -H "Authorization: token ${{ secrets.RUNNER_READER_TOKEN }}" "https://api.github.com/orgs/thegangtechnology/actions/runners")
          available=$(echo "$runners" | jq '.runners[] | select(.status == "online" )')
          echo $available
          if [ -n "$available" ]; then
            echo "runner-label=self-hosted"
            echo "runner-label=self-hosted" >> $GITHUB_OUTPUT
          else
            echo "runner-label=ubuntu-latest"
            echo "runner-label=ubuntu-latest" >> $GITHUB_OUTPUT
          fi

  test:
    needs: [ check-runner ]
    runs-on: ${{ needs.check-runner.outputs.runner-label }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'  # Specify the Python version you need

    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -

    - name: Install dependencies
      run: |
        poetry install

    - name: Run pre-commit
      run: poetry run pre-commit run --all-files

    - name: Run pytest
      run: poetry run pytest -m "not stress_test"
