name: Publish package

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+*'
    branches:
      - jeep/*
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  PYTHON_VERSION: '3.13'
  POETRY_VERSION: '2.1.3'

jobs:
  check-runner:
    runs-on: ubuntu-latest
    outputs:
      runner-label: ${{ steps.set-runner.outputs.runner-label }}
    steps:
      - name: Set runner
        id: set-runner
        run: |
          runners=$(curl -s -H "Accept: application/vnd.github+json" -H "Authorization: token ${{ secrets.RUNNER_READER_TOKEN }}" "https://api.github.com/orgs/thegangtechnology/actions/runners")
          available=$(echo "$runners" | jq '.runners[] | select(.status == "online" )')
          echo $available
          if [ -n "$available" ]; then
            echo "runner-label=self-hosted"
            echo "runner-label=self-hosted" >> $GITHUB_OUTPUT
          else
            echo "runner-label=ubuntu-latest"
            echo "runner-label=ubuntu-latest" >> $GITHUB_OUTPUT
          fi

  get-env:
    needs: check-runner
    name: Get Environment vars
    runs-on: ${{ needs.check-runner.outputs.runner-label }}
    outputs:
      PYTHON_VERSION: ${{ env.PYTHON_VERSION }}
      POETRY_VERSION: ${{ env.POETRY_VERSION }}
    steps:
      - run: |
          [[ "${{ env.PYTHON_VERSION }}" == "x.yz" ]] && echo "Please set PYTHON_VERSION" && exit 1 || exit 0


  publish:
    needs: [ check-runner, get-env ]
    uses: thegangtechnology/shared-workflow/.github/workflows/github-publish-pythonpackage.yml@jeep/fix-gh-publish
    with:
      runner: ${{ needs.check-runner.outputs.runner-label }}
      python-version: ${{ needs.get-env.outputs.PYTHON_VERSION }}
      poetry-version: ${{ needs.get-env.outputs.POETRY_VERSION }}
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
